import Head from 'next/head'
import Image from 'next/image'
import From from '../components/form'
import Table from '../components/table'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
  const [visible,setVisible]=useState(false);

  const handler=()=>{
    setVisible(!visible)
  }
  return (
    <section>
    <div className={styles.container}>
      <Head>
        <title>Crud application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main>
    <div>
    <h1>Employee Management</h1>
    <button onClick={handler}>Add Employee</button>
    </div>

    <div className="container mx-auto">
      {visible?<From></From>:<></>}
    </div>

    {/* table */}
    <div className="container mx-auto">
    <Table></Table>
    </div>
     </main>
    </div>
    </section>
  )
}
